# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/webserv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/webserv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/webserv/CMakeFiles /workspaces/webserv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/webserv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named webserv

# Build rule for target.
webserv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webserv
.PHONY : webserv

# fast build rule for target.
webserv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/build
.PHONY : webserv/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/AConfigBlock.o: src/AConfigBlock.cpp.o
.PHONY : src/AConfigBlock.o

# target to build an object file
src/AConfigBlock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/AConfigBlock.cpp.o
.PHONY : src/AConfigBlock.cpp.o

src/AConfigBlock.i: src/AConfigBlock.cpp.i
.PHONY : src/AConfigBlock.i

# target to preprocess a source file
src/AConfigBlock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/AConfigBlock.cpp.i
.PHONY : src/AConfigBlock.cpp.i

src/AConfigBlock.s: src/AConfigBlock.cpp.s
.PHONY : src/AConfigBlock.s

# target to generate assembly for a file
src/AConfigBlock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/AConfigBlock.cpp.s
.PHONY : src/AConfigBlock.cpp.s

src/AParser.o: src/AParser.cpp.o
.PHONY : src/AParser.o

# target to build an object file
src/AParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/AParser.cpp.o
.PHONY : src/AParser.cpp.o

src/AParser.i: src/AParser.cpp.i
.PHONY : src/AParser.i

# target to preprocess a source file
src/AParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/AParser.cpp.i
.PHONY : src/AParser.cpp.i

src/AParser.s: src/AParser.cpp.s
.PHONY : src/AParser.s

# target to generate assembly for a file
src/AParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/AParser.cpp.s
.PHONY : src/AParser.cpp.s

src/Client.o: src/Client.cpp.o
.PHONY : src/Client.o

# target to build an object file
src/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Client.cpp.o
.PHONY : src/Client.cpp.o

src/Client.i: src/Client.cpp.i
.PHONY : src/Client.i

# target to preprocess a source file
src/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Client.cpp.i
.PHONY : src/Client.cpp.i

src/Client.s: src/Client.cpp.s
.PHONY : src/Client.s

# target to generate assembly for a file
src/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Client.cpp.s
.PHONY : src/Client.cpp.s

src/Config.o: src/Config.cpp.o
.PHONY : src/Config.o

# target to build an object file
src/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Config.cpp.o
.PHONY : src/Config.cpp.o

src/Config.i: src/Config.cpp.i
.PHONY : src/Config.i

# target to preprocess a source file
src/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Config.cpp.i
.PHONY : src/Config.cpp.i

src/Config.s: src/Config.cpp.s
.PHONY : src/Config.s

# target to generate assembly for a file
src/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Config.cpp.s
.PHONY : src/Config.cpp.s

src/Environment.o: src/Environment.cpp.o
.PHONY : src/Environment.o

# target to build an object file
src/Environment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Environment.cpp.o
.PHONY : src/Environment.cpp.o

src/Environment.i: src/Environment.cpp.i
.PHONY : src/Environment.i

# target to preprocess a source file
src/Environment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Environment.cpp.i
.PHONY : src/Environment.cpp.i

src/Environment.s: src/Environment.cpp.s
.PHONY : src/Environment.s

# target to generate assembly for a file
src/Environment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Environment.cpp.s
.PHONY : src/Environment.cpp.s

src/Location.o: src/Location.cpp.o
.PHONY : src/Location.o

# target to build an object file
src/Location.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Location.cpp.o
.PHONY : src/Location.cpp.o

src/Location.i: src/Location.cpp.i
.PHONY : src/Location.i

# target to preprocess a source file
src/Location.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Location.cpp.i
.PHONY : src/Location.cpp.i

src/Location.s: src/Location.cpp.s
.PHONY : src/Location.s

# target to generate assembly for a file
src/Location.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Location.cpp.s
.PHONY : src/Location.cpp.s

src/ParseConfig.o: src/ParseConfig.cpp.o
.PHONY : src/ParseConfig.o

# target to build an object file
src/ParseConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/ParseConfig.cpp.o
.PHONY : src/ParseConfig.cpp.o

src/ParseConfig.i: src/ParseConfig.cpp.i
.PHONY : src/ParseConfig.i

# target to preprocess a source file
src/ParseConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/ParseConfig.cpp.i
.PHONY : src/ParseConfig.cpp.i

src/ParseConfig.s: src/ParseConfig.cpp.s
.PHONY : src/ParseConfig.s

# target to generate assembly for a file
src/ParseConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/ParseConfig.cpp.s
.PHONY : src/ParseConfig.cpp.s

src/ParseRequest.o: src/ParseRequest.cpp.o
.PHONY : src/ParseRequest.o

# target to build an object file
src/ParseRequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/ParseRequest.cpp.o
.PHONY : src/ParseRequest.cpp.o

src/ParseRequest.i: src/ParseRequest.cpp.i
.PHONY : src/ParseRequest.i

# target to preprocess a source file
src/ParseRequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/ParseRequest.cpp.i
.PHONY : src/ParseRequest.cpp.i

src/ParseRequest.s: src/ParseRequest.cpp.s
.PHONY : src/ParseRequest.s

# target to generate assembly for a file
src/ParseRequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/ParseRequest.cpp.s
.PHONY : src/ParseRequest.cpp.s

src/RequestHandler.o: src/RequestHandler.cpp.o
.PHONY : src/RequestHandler.o

# target to build an object file
src/RequestHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/RequestHandler.cpp.o
.PHONY : src/RequestHandler.cpp.o

src/RequestHandler.i: src/RequestHandler.cpp.i
.PHONY : src/RequestHandler.i

# target to preprocess a source file
src/RequestHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/RequestHandler.cpp.i
.PHONY : src/RequestHandler.cpp.i

src/RequestHandler.s: src/RequestHandler.cpp.s
.PHONY : src/RequestHandler.s

# target to generate assembly for a file
src/RequestHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/RequestHandler.cpp.s
.PHONY : src/RequestHandler.cpp.s

src/ServerConfig.o: src/ServerConfig.cpp.o
.PHONY : src/ServerConfig.o

# target to build an object file
src/ServerConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/ServerConfig.cpp.o
.PHONY : src/ServerConfig.cpp.o

src/ServerConfig.i: src/ServerConfig.cpp.i
.PHONY : src/ServerConfig.i

# target to preprocess a source file
src/ServerConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/ServerConfig.cpp.i
.PHONY : src/ServerConfig.cpp.i

src/ServerConfig.s: src/ServerConfig.cpp.s
.PHONY : src/ServerConfig.s

# target to generate assembly for a file
src/ServerConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/ServerConfig.cpp.s
.PHONY : src/ServerConfig.cpp.s

src/StringUtils.o: src/StringUtils.cpp.o
.PHONY : src/StringUtils.o

# target to build an object file
src/StringUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/StringUtils.cpp.o
.PHONY : src/StringUtils.cpp.o

src/StringUtils.i: src/StringUtils.cpp.i
.PHONY : src/StringUtils.i

# target to preprocess a source file
src/StringUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/StringUtils.cpp.i
.PHONY : src/StringUtils.cpp.i

src/StringUtils.s: src/StringUtils.cpp.s
.PHONY : src/StringUtils.s

# target to generate assembly for a file
src/StringUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/StringUtils.cpp.s
.PHONY : src/StringUtils.cpp.s

src/httpRequest.o: src/httpRequest.cpp.o
.PHONY : src/httpRequest.o

# target to build an object file
src/httpRequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/httpRequest.cpp.o
.PHONY : src/httpRequest.cpp.o

src/httpRequest.i: src/httpRequest.cpp.i
.PHONY : src/httpRequest.i

# target to preprocess a source file
src/httpRequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/httpRequest.cpp.i
.PHONY : src/httpRequest.cpp.i

src/httpRequest.s: src/httpRequest.cpp.s
.PHONY : src/httpRequest.s

# target to generate assembly for a file
src/httpRequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/httpRequest.cpp.s
.PHONY : src/httpRequest.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... webserv"
	@echo "... src/AConfigBlock.o"
	@echo "... src/AConfigBlock.i"
	@echo "... src/AConfigBlock.s"
	@echo "... src/AParser.o"
	@echo "... src/AParser.i"
	@echo "... src/AParser.s"
	@echo "... src/Client.o"
	@echo "... src/Client.i"
	@echo "... src/Client.s"
	@echo "... src/Config.o"
	@echo "... src/Config.i"
	@echo "... src/Config.s"
	@echo "... src/Environment.o"
	@echo "... src/Environment.i"
	@echo "... src/Environment.s"
	@echo "... src/Location.o"
	@echo "... src/Location.i"
	@echo "... src/Location.s"
	@echo "... src/ParseConfig.o"
	@echo "... src/ParseConfig.i"
	@echo "... src/ParseConfig.s"
	@echo "... src/ParseRequest.o"
	@echo "... src/ParseRequest.i"
	@echo "... src/ParseRequest.s"
	@echo "... src/RequestHandler.o"
	@echo "... src/RequestHandler.i"
	@echo "... src/RequestHandler.s"
	@echo "... src/ServerConfig.o"
	@echo "... src/ServerConfig.i"
	@echo "... src/ServerConfig.s"
	@echo "... src/StringUtils.o"
	@echo "... src/StringUtils.i"
	@echo "... src/StringUtils.s"
	@echo "... src/httpRequest.o"
	@echo "... src/httpRequest.i"
	@echo "... src/httpRequest.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

